go.property("owner", hash("none"))
go.property("x", 0)
go.property("y", 0)
go.property("x_next", 0)
go.property("y_next", 0)
go.property("angle", 0)

function init(self)
	msg.post("#ss", "play_animation", 
		{ id = self.owner })
	go.set(".", "position", vmath.vector3(self.x, self.y, 0))
	--go.set("./left_def", "position", vmath.vector3(50, 100, 0))
	go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, 
	vmath.vector3(self.x_next, self.y_next, 0), go.EASING_LINEAR, 0.2)
end
